### ISSUE TITLE
[stgp demo] RuntimeError: Trying to backward through the graph a second time

### ISSUE THREAD

**Issue by zen-xingle** [IceLab-X/Mini-GP#13]
https://github.com/IceLab-X/Mini-GP/blob/a72779a0b4a178e987e663ed4893763633d9e82a/stgp_demo.py#L15 
this line leads to the error.

The nn.parameter object is not collect, but only maintain the exp result unchanged despite of the training.

**Comment by Fillip1233** [comment]
Thank you for raising this question and the solution. I have set the data to nn.Parameter and solved the problem.
